global using System.IO;
global using System.Net.Http;
global using Application = System.Windows.Application;
global using MessageBox = System.Windows.MessageBox;
global using MessageBoxButton = System.Windows.MessageBoxButton;
global using MessageBoxImage = System.Windows.MessageBoxImage;
global using UserControl = System.Windows.Controls.UserControl;
global using Button = System.Windows.Controls.Button;
global using TextBox = System.Windows.Controls.TextBox;
global using CheckBox = System.Windows.Controls.CheckBox;
global using ComboBox = System.Windows.Controls.ComboBox;
global using StackPanel = System.Windows.Controls.StackPanel;
global using DockPanel = System.Windows.Controls.DockPanel;
global using Border = System.Windows.Controls.Border;
global using ScrollViewer = System.Windows.Controls.ScrollViewer;
global using ListBox = System.Windows.Controls.ListBox;
global using ListBoxItem = System.Windows.Controls.ListBoxItem;
global using PasswordBox = System.Windows.Controls.PasswordBox;
global using Grid = System.Windows.Controls.Grid;
global using Image = System.Windows.Controls.Image;
global using Orientation = System.Windows.Controls.Orientation;
global using Clipboard = System.Windows.Clipboard;
